version: '3'

services:
  rsync:
    build:
      args:
        - TARGETARCH=amd64
      context: .
    environment:
      - 'RSYNC_EVERY_X_HOURS=1' # rsync every hour
      - 'RSYNC_SRC_DIRS=/src1 /src2'
    volumes:
      - ./dest:/dest
      - ./src1:/src1
      - ./src2:/src2
